stages:
  - setup
  - build
  - test

variables:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "3.16.2" # Update to the desired Flutter version

before_script:
  - apt-get update -qq
  - apt-get install -y lib32stdc++6
  - export PATH="$PATH":"$HOME/.pub-cache/bin"
  - flutter channel $FLUTTER_CHANNEL
  - flutter upgrade --force
  - flutter config --enable-web
  - flutter pub get

install_dependencies:
  stage: setup
  script:
    - echo "Installing Flutter dependencies..."

build_project:
  stage: build
  script:
    - echo "Building the Flutter project..."
    - flutter build web

flutter_test:
  stage: test
  script:
    - ./testRunner.sh ## This is your shell file path which has test execution command

  tags:
    - testRunnerMachine

  artifacts: ## Stroing the xml report as artifacts
    when: always
    reports:
      junit:
        - junit-report.xml
